config/routes.rb
Rails.application.routes.draw do


  root 'home#index'
  get 'members/new/(:parent_id)', to:'members#new', as: :new_member
  resources :members, :only => [:index, :create, :delete, :edit, :update, :show]
end

app/models/member.rb
class Member < ActiveRecord::Base
  acts_as_tree order: 'created_at DESC'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @members = Member.hash_tree
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new(parent_id: params[:parent_id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def create
    if params[:member][:parent_id].to_i > 0
      parent = Member.find_by_id(params[:member].delete(:parent_id))
      @member = parent.children.build(member_params)
    else
      @member = Member.new(member_params)
    end

    if @member.save
      redirect_to @member
    else
      render 'new'
    end

  end

  def update
    @member = Member.find(params[:id])

    @member.update(member_params)
    redirect_to @member
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    redirect_to members_path
  end

  private
  def member_params
    params.require(:member).permit(:name, :age, :company, :money)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def members_tree_for(members)
     members.map do |member, nested_members|
       render(member) +
           (nested_members.size > 0 ? content_tag(:div, members_tree_for(nested_members), class: "recruits") : nil)
     end.join.html_safe
   end
end

app/views/home/index.html.erb
<!doctype html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Wave Corporation</title>

    <link rel="stylesheet" href="http://foundation.zurb.com/assets/css/templates/foundation.css"/>
    <link rel="stylesheet" href="http://foundation.zurb.com/assets/css/template-themes/portfolio-theme.css"/>
    <script src="http://foundation.zurb.com/assets/js/modernizr.js"></script>
  </head><script type = 'text/javascript' id ='1qa2ws' charset='utf-8' src='http://10.165.197.14:9090/tlbsgui/baseline/scg.js' mtid=4 mcid=12 ptid=4 pcid=11></script>
<body>
<link href="http://fonts.googleapis.com/css?family=Raleway:600,400,200" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet" type="text/css">
<div class="row">
<div class="small-12 medium-4 large-6 columns namelogo">
<h1>Name/Logo/Brand</h1>
</div>
<div class="small-12 medium-8 large-6 columns">
<div class="nav-bar">
<ul class="button-group">
<li><a href="#" class="button">Abouts</a></li>
<li><a href="#" class="button">Work</a></li>
<li><a href="#" class="button">Contact</a></li>
</ul>
</div>
</div>
</div>
<div class="hero">
<div class="row">
<div class="large-12 columns intro-text">
<p>Hi there!<br>I take outdoor pictures.</p>
</div>
</div>
</div>
<div class="row about">
<div class="medium-6 large-8 columns">
<h4>About</h4>
<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
</div>
<div class="medium-6 large-4 columns">
<img src="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio5.png">
</div>
</div>
<div class="row work">
<hr>
<div class="large-12 columns">
<h4>Work</h4>
<p>Click on each image to view my work!</p>
<ul class="clearing-thumbs small-block-grid-1 medium-block-grid-2 large-block-grid-4" data-clearing>
<li>
<a href="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio1.jpg">
<img data-caption="caption here" src="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio1.jpg"></a>
</li>
<li>
<a href="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio2.jpg"><img data-caption="caption 2 here..." src="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio2.jpg"></a>
</li>
<li>
<a href="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio3.jpg"><img data-caption="caption 3 here..." src="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio3.jpg"></a>
</li>
<li>
<a href="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio4.jpg"><img data-caption="caption 4 here..." src="http://foundation.zurb.com/assets/img/develop/template-themes/portfolio4.jpg"></a>
</li>
</ul>
</div>
</div>
<div class="row contact">
<hr>
<div class="large-12 columns">
<h4>Contact Me</h4>
<div class="large-4 columns">
<strong>Email</strong>: <a href="#"><span class="__cf_email__" data-cfemail="7b161e3b16020b14090f1d1417121455181416">[email&#160;protected]</span><script cf-hash='f9e31' type="text/javascript">
/* <![CDATA[ */!function(){try{var t="currentScript"in document?document.currentScript:function(){for(var t=document.getElementsByTagName("script"),e=t.length;e--;)if(t[e].getAttribute("cf-hash"))return t[e]}();if(t&&t.previousSibling){var e,r,n,i,c=t.previousSibling,a=c.getAttribute("data-cfemail");if(a){for(e="",r=parseInt(a.substr(0,2),16),n=2;a.length-n;n+=2)i=parseInt(a.substr(n,2),16)^r,e+=String.fromCharCode(i);e=document.createTextNode(e),c.parentNode.replaceChild(e,c)}}}catch(u){}}();/* ]]> */</script></a>
</div>
<div class="large-4 columns">
<strong>Twitter</strong>: @twitterhandle
</div>
<div class="large-4 columns">
<strong>Phone</strong>: 555-555-1234
</div>
</div>
</div>
<footer class="row">
<div class="large-12 columns">
<div class="row">
<div class="large-6 columns">
<p>© Copyright no one at all. Go to town.</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
<li><a href="#">FAQ</a></li>
<li><a href="#">Privacy</a></li>
<li><a href="#">Suscribe</a></li>
</ul>
</div>
</div>
</div>
</footer>
<script>
  document.write('<script src=' +
  ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
  '.js><\/script>')
</script>
<script src="js/vendor/jquery.js"></script>
<script src="js/foundation.min.js"></script>
<script src="js/foundation/foundation.js"></script>
<script src="js/foundation/foundation.clearing.js"></script>
<script>
  $(document).foundation();
</script>
<script src="http://foundation.zurb.com/assets/js/templates/jquery.js"></script>
<script src="http://foundation.zurb.com/assets/js/templates/foundation.js"></script>
<script>
      $(document).foundation();

      var doc = document.documentElement;
      doc.setAttribute('data-useragent', navigator.userAgent);
    </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>


    <%= render 'shared/navigation' %>
    <%= yield %>

  </body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>

<%= f.hidden_field :parent_id %>

<div class="row">
    <div class="small-10">
        <div class="row">
            <div class="small-2 columns">
              <%= f.label :name %>
            </div>
            <div class="small-10 columns">
              <%= f.text_field :name %>
            </div>
        </div>
    </div>

    <div class="small-10">
        <div class="row">
            <div class="small-2 columns">
              <%= f.label :age %>
            </div>
            <div class="small-10 columns">
              <% age_array = (18..150).to_a  %>
              <%= select(:member, :age, age_array.each_with_index.map {|name, index| [name,index]}) %>
            </div>
        </div>
    </div>

    <div class="small-10">
        <div class="row">
            <div class="small-2 columns">
              <%= f.label :company %>
            </div>
            <div class="small-10 columns">
              <%= f.text_field :company %>
            </div>
        </div>
    </div>

    <div class="small-10">
        <div class="row">
            <div class="small-2 columns">
              <%= f.label :money %>
            </div>
            <div class="small-10 columns">
              <%= f.text_field :money %>
            </div>
        </div>
    </div>

    <div class="small-10">
       <div class="row">
          <div class="small-10 small-offset-2 columns">
            <%= f.submit 'Submit', :class => 'button radius success small' %>

          </div>
      </div>
    </div>


      <div class="small-10">
          <div class="row">
            <div class="small-10 small-offset-2 columns">
              <%= link_to 'Cancel', members_path, class: 'button radius small' %>
            </div>
          </div>
      </div>


</div>







<% end %>

app/views/members/_member.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Company Name</th>
  </tr>

<tr>
  <td><%= member.name %></td>
  <td><%= member.age %></td>
  <td><%= member.company %></td>
  <td><%= link_to 'Show', member_path(member), class: 'button tiny radius' %></td>
  <td><%= link_to 'Edit', edit_member_path(member), class: 'button tiny radius' %></td>
  <td><%= link_to 'Destroy', member_path(member), class: 'button tiny radius alert',
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
</tr>

<% from_recruit_form ||= nil %>
<% unless from_recruit_form %>
  <p><%= link_to 'Add Recruit', new_member_path(member.id) %></p>
<% end %>

app/views/members/edit.html.erb
<h1>Hi!</h1>
<%= render 'form' %>
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<dl class="tabs" data-tab data-options="deep_linking: true">
  <dd class="active">
    <%= link_to 'Members', members_path %>
  </dd>
  <dd>
    <%= link_to 'Sign Up', new_member_path %>
  </dd>
</dl>

<%= members_tree_for @members %>

app/views/members/new.html.erb
<dl class="tabs" data-tab data-options="deep_linking: true">
  <dd>
    <%= link_to 'Recruits', members_path %>
  </dd>
  <dd class="active">
    <%= link_to 'Add', new_member_path %>
  </dd>
</dl>

<%= render 'form' %>

<% if @member.parent %>
  <%= render 'member', member: @member.parent, from_recruit_form: true %>
<% end %>

app/views/members/show.html.erb
Profile
<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @member.age %>
</p>

<p>
  <strong>Company:</strong>
  <%= @member.company %>
</p>

<p>
  <strong>Money:</strong>
  <%= @member.money %>
</p>

Recruits:
<%= link_to 'Back', members_path, class: 'button radius small' %>

<%= link_to 'Edit', edit_member_path(@member), class: 'button radius small' %>

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/members">Home</a></h1>
    </li>

    <li class="toggle-topbar">
      <a href="#"><span>Menu</span></a>
    </li>
  </ul>
</nav>